repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      types: [file]  # override `types: [python]`
      files: (\.py$|^SConstruct$|^SConscript$)
      exclude: (tests|examples)/.*/lib  # Ignore 3rd party stuff
      args:
          - "--line-length=100"
      language_version: python3
